[2024-02-18T20:02:27.936+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_dag.insert_into_postgres manual__2024-02-18T20:02:23.272493+00:00 [queued]>
[2024-02-18T20:02:27.941+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_dag.insert_into_postgres manual__2024-02-18T20:02:23.272493+00:00 [queued]>
[2024-02-18T20:02:27.941+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-18T20:02:27.948+0000] {taskinstance.py:2191} INFO - Executing <Task(PostgresOperator): insert_into_postgres> on 2024-02-18 20:02:23.272493+00:00
[2024-02-18T20:02:27.952+0000] {standard_task_runner.py:60} INFO - Started process 4315 to run task
[2024-02-18T20:02:27.955+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'api_dag', 'insert_into_postgres', 'manual__2024-02-18T20:02:23.272493+00:00', '--job-id', '82', '--raw', '--subdir', 'DAGS_FOLDER/api_dag.py', '--cfg-path', '/tmp/tmpojveue9k']
[2024-02-18T20:02:27.955+0000] {standard_task_runner.py:88} INFO - Job 82: Subtask insert_into_postgres
[2024-02-18T20:02:27.984+0000] {task_command.py:423} INFO - Running <TaskInstance: api_dag.insert_into_postgres manual__2024-02-18T20:02:23.272493+00:00 [running]> on host 482b276ff4ae
[2024-02-18T20:02:28.037+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='api_dag' AIRFLOW_CTX_TASK_ID='insert_into_postgres' AIRFLOW_CTX_EXECUTION_DATE='2024-02-18T20:02:23.272493+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-18T20:02:23.272493+00:00'
[2024-02-18T20:02:28.038+0000] {sql.py:276} INFO - Executing: INSERT INTO automezzo (id) VALUES (%(task_instance)s);
[2024-02-18T20:02:28.043+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-02-18T20:02:28.048+0000] {base.py:83} INFO - Using connection ID 'postgres_conn' for task execution.
[2024-02-18T20:02:29.194+0000] {sql.py:450} INFO - Running statement: INSERT INTO automezzo (id) VALUES (%(task_instance)s);, parameters: {'param_id': '45499'}
[2024-02-18T20:02:29.196+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 398, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 453, in _run_command
    cur.execute(sql_statement, parameters)
KeyError: 'task_instance'
[2024-02-18T20:02:29.208+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=api_dag, task_id=insert_into_postgres, execution_date=20240218T200223, start_date=20240218T200227, end_date=20240218T200229
[2024-02-18T20:02:29.228+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 82 for task insert_into_postgres ('task_instance'; 4315)
[2024-02-18T20:02:29.254+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-18T20:02:29.278+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
