[2024-02-18T21:10:25.873+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: api_dag.insert_into_postgres manual__2024-02-18T21:10:20.940537+00:00 [queued]>
[2024-02-18T21:10:25.878+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: api_dag.insert_into_postgres manual__2024-02-18T21:10:20.940537+00:00 [queued]>
[2024-02-18T21:10:25.878+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-18T21:10:25.887+0000] {taskinstance.py:2191} INFO - Executing <Task(PostgresOperator): insert_into_postgres> on 2024-02-18 21:10:20.940537+00:00
[2024-02-18T21:10:25.891+0000] {standard_task_runner.py:60} INFO - Started process 5551 to run task
[2024-02-18T21:10:25.893+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'api_dag', 'insert_into_postgres', 'manual__2024-02-18T21:10:20.940537+00:00', '--job-id', '149', '--raw', '--subdir', 'DAGS_FOLDER/api_dag.py', '--cfg-path', '/tmp/tmplc7jzkat']
[2024-02-18T21:10:25.894+0000] {standard_task_runner.py:88} INFO - Job 149: Subtask insert_into_postgres
[2024-02-18T21:10:25.923+0000] {task_command.py:423} INFO - Running <TaskInstance: api_dag.insert_into_postgres manual__2024-02-18T21:10:20.940537+00:00 [running]> on host 482b276ff4ae
[2024-02-18T21:10:25.953+0000] {abstractoperator.py:707} ERROR - Exception rendering Jinja template for task 'insert_into_postgres', field 'parameters'. Template: {'id': "{{ task_instance.xcom_pull(task_ids='transform_data_task') | extract_id }}", 'telaio': '233015'}
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 699, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 186, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 186, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 173, in render_template
    template = jinja_env.from_string(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateAssertionError: No filter named 'extract_id'.
[2024-02-18T21:10:25.954+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2334, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2465, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2877, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/baseoperator.py", line 1241, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/abstractoperator.py", line 699, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 186, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 186, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 173, in render_template
    template = jinja_env.from_string(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateAssertionError: No filter named 'extract_id'.
[2024-02-18T21:10:25.959+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=api_dag, task_id=insert_into_postgres, execution_date=20240218T211020, start_date=20240218T211025, end_date=20240218T211025
[2024-02-18T21:10:25.966+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 149 for task insert_into_postgres (No filter named 'extract_id'.; 5551)
[2024-02-18T21:10:25.985+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-02-18T21:10:25.997+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
